---
- name: Check if jcmd is installed
  command: "which jcmd"
  register: jcmd_result
  ignore_errors: true

- name: Display status based on jcmd presence
  debug:
    msg: >
      {% if jcmd_result.rc == 0 %}
      jcmd is installed.
      {% else %}
      Warning: jcmd is not installed. Java applications will not be detected automatically.
      {% endif %}
