---
- name: Check sfagent service status
  ansible.builtin.command: systemctl is-active --quiet sfagent
  register: sfagent_status
  failed_when: sfagent_status.rc != 0

- name: Report sfagent service status
  ansible.builtin.debug:
    msg: "Service sfagent is {{ 'running.' if sfagent_status.rc == 0 else 'not running. Check service sfagent status or systemctl status sfagent.' }}"

