#******************************************************#
#* Copyright 2019-20, MapleLabs, All Rights Reserved. *#
#*                                                    *# 
#******************************************************#
---

# Configure SnappyFlow Agents
- include_tasks:
    file: pre-install.yml
    apply:
      tags:
        - install
  tags:
    - always

- include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - always

- include_tasks:
    file: validate.yml
    apply:
      tags:
        - install
  tags:
    - always

- include_tasks:
    file: upgrade.yml
    apply:
      tags:
        - upgrade
  tags:
    - always
